networks:
  task-tracker-net:
services:
  db:
    container_name: database
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: task-tracker-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  migration:
    image: liquibase/liquibase:4.30
    container_name: liquibase
    depends_on:
      - db
    command:
      - --search-path=/liquibase/changelog
      - --changelog-file=db.changelog-master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://db:5432/task-tracker-db
      - --username=postgres
      - --password=password
      - update
    volumes:
    - /Users/maksimignatov/IdeaProjects/task-tracker-ms/task-tracker-api/src/main/resources/db/changelog:/liquibase/changelog

  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka1:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka1
    container_name: kafka1
    ports:
      - "29091:29091"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091,PLAINTEXT_HOST://Localhost:29091
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9091,PLAINTEXT_HOST://0.0.0.0:29091
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      BOOTSTRAP_SERVERS: kafka1:9091,kafka2:9092
    depends_on:
      - zookeeper

  kafka2:
    image: confluentinc/cp-kafka:7.7.1
    hostname: kafka2
    container_name: kafka2
    ports:
      - "29092:29092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,PLAINTEXT_HOST://Localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
      BOOTSTRAP_SERVERS: kafka1:9091,kafka2:9092

    depends_on:
      - zookeeper

  init-kafka:
    image: confluentinc/cp-kafka:7.7.1
    depends_on:
      - kafka1
      - kafka2
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka1:9091,kafka2:9092 --list || true

      echo 'Creating kafka topics...'
      kafka-topics --bootstrap-server kafka1:9091,kafka2:9092 --create --if-not-exists --topic EMAIL_SENDING_TASKS --replication-factor 2 --partitions 2

      echo 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka1:9091,kafka2:9092 --list
      "

  task-tracker-email-sender:
    build:
      context: .
      dockerfile: task-tracker-email-sender/Dockerfile
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka1:9091,kafka2:9092
    env_file:
      - .env

  task-tracker-api:
    build:
      context: .
      dockerfile: task-tracker-api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - migration
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/task-tracker-db
    env_file:
      - .env

  task-tracker-scheduler:
    build:
      context: .
      dockerfile: task-tracker-scheduler/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env